version: '3.3'
services:
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker-data/data:/usr/local/redis/data
      - ./docker-data/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./docker-data/logs:/usr/local/redis/logs
    command: ["redis-server","/usr/local/redis/conf/redis.conf"]
